### ISSUE TITLE
Issue matching unrelated words. 

### ISSUE THREAD

**Issue by dsivasuthan** [ajeetdsouza/clidle#3]
![Screenshot_20220205-181008_Termux](https://user-images.githubusercontent.com/1507367/152662070-0478b156-bc86-4add-b91f-19c92745c980.png)

**Comment by ajeetdsouza** [comment]
Hey, can you help me with what exactly is wrong here?

**Comment by dsivasuthan** [comment]
Several issues:
1. Correct word is OUTDO but matches substring TOO
2. It fails to match letters that were matched in previous row.

**Comment by ajeetdsouza** [comment]
I think you may have misunderstood the instructions. I've added a how-to-play to the README, could you take a look?

T, O, and O turn yellow because all 3 letters are present in the word OUTDO. Since there are two O's in OUTDO, both the O's in your guess turned yellow. If your guess had a letter in the correct _position_, it would have turned green instead.

**Comment by dsivasuthan** [comment]
I see, I get it now. I thought that was green which led to the confusion (or I thought that's how Termux interpreted green). Anyways, I will give this another shot. Thanks for creating this. I love doing things in the terminal and this is awesome, specially cuz I don't have to install anything. 

I am closing this ticket.
